#ifndef ROOT_Rtypes
#include "Rtypes.h"
#endif

class TTree;

namespace bs2st_bu2kmutau {

  namespace bs2st2buk_kmux {

    struct Bs2st {
      Double_t              ENDVERTEX_X;
      Double_t              ENDVERTEX_Y;
      Double_t              ENDVERTEX_Z;
      Double_t              ENDVERTEX_XERR;
      Double_t              ENDVERTEX_YERR;
      Double_t              ENDVERTEX_ZERR;
      Double_t              ENDVERTEX_CHI2;
      Int_t                 ENDVERTEX_NDOF;
      Float_t               ENDVERTEX_COV_;
      Double_t              OWNPV_X;
      Double_t              OWNPV_Y;
      Double_t              OWNPV_Z;
      Double_t              OWNPV_XERR;
      Double_t              OWNPV_YERR;
      Double_t              OWNPV_ZERR;
      Double_t              OWNPV_CHI2;
      Int_t                 OWNPV_NDOF;
      Float_t               OWNPV_COV_;
      Double_t              IP_OWNPV;
      Double_t              IPCHI2_OWNPV;
      Double_t              FD_OWNPV;
      Double_t              FDCHI2_OWNPV;
      Double_t              DIRA_OWNPV;
      Double_t              P;
      Double_t              PT;
      Double_t              PE;
      Double_t              PX;
      Double_t              PY;
      Double_t              PZ;
      Double_t              MM;
      Double_t              MMERR;
      Double_t              M;
      Int_t                 ID;
      Bool_t                L0Global_Dec;
      Bool_t                L0Global_TIS;
      Bool_t                L0Global_TOS;
      Bool_t                Hlt1Global_Dec;
      Bool_t                Hlt1Global_TIS;
      Bool_t                Hlt1Global_TOS;
      Bool_t                Hlt1Phys_Dec;
      Bool_t                Hlt1Phys_TIS;
      Bool_t                Hlt1Phys_TOS;
      Bool_t                Hlt2Global_Dec;
      Bool_t                Hlt2Global_TIS;
      Bool_t                Hlt2Global_TOS;
      Bool_t                Hlt2Phys_Dec;
      Bool_t                Hlt2Phys_TIS;
      Bool_t                Hlt2Phys_TOS;
      Double_t              BPVDIRA;
      Double_t              BPVIPCHI2;
      Double_t              ETA;
      Double_t              MIPCHI2DV;
      Double_t              PHI;
      Double_t              PID;
      Double_t              VCHI2PDOF;

    };

    struct Bu {

      Double_t              CosTheta;
      Double_t              ENDVERTEX_X;
      Double_t              ENDVERTEX_Y;
      Double_t              ENDVERTEX_Z;
      Double_t              ENDVERTEX_XERR;
      Double_t              ENDVERTEX_YERR;
      Double_t              ENDVERTEX_ZERR;
      Double_t              ENDVERTEX_CHI2;
      Int_t                 ENDVERTEX_NDOF;
      Float_t               ENDVERTEX_COV_;
      Double_t              OWNPV_X;
      Double_t              OWNPV_Y;
      Double_t              OWNPV_Z;
      Double_t              OWNPV_XERR;
      Double_t              OWNPV_YERR;
      Double_t              OWNPV_ZERR;
      Double_t              OWNPV_CHI2;
      Int_t                 OWNPV_NDOF;
      Float_t               OWNPV_COV_;
      Double_t              IP_OWNPV;
      Double_t              IPCHI2_OWNPV;
      Double_t              FD_OWNPV;
      Double_t              FDCHI2_OWNPV;
      Double_t              DIRA_OWNPV;
      Double_t              ORIVX_X;
      Double_t              ORIVX_Y;
      Double_t              ORIVX_Z;
      Double_t              ORIVX_XERR;
      Double_t              ORIVX_YERR;
      Double_t              ORIVX_ZERR;
      Double_t              ORIVX_CHI2;
      Int_t                 ORIVX_NDOF;
      Float_t               ORIVX_COV_;
      Double_t              FD_ORIVX;
      Double_t              FDCHI2_ORIVX;
      Double_t              DIRA_ORIVX;
      Double_t              P;
      Double_t              PT;
      Double_t              PE;
      Double_t              PX;
      Double_t              PY;
      Double_t              PZ;
      Double_t              MM;
      Double_t              MMERR;
      Double_t              M;
      Int_t                 ID;
      Bool_t                L0Global_Dec;
      Bool_t                L0Global_TIS;
      Bool_t                L0Global_TOS;
      Bool_t                Hlt1Global_Dec;
      Bool_t                Hlt1Global_TIS;
      Bool_t                Hlt1Global_TOS;
      Bool_t                Hlt1Phys_Dec;
      Bool_t                Hlt1Phys_TIS;
      Bool_t                Hlt1Phys_TOS;
      Bool_t                Hlt2Global_Dec;
      Bool_t                Hlt2Global_TIS;
      Bool_t                Hlt2Global_TOS;
      Bool_t                Hlt2Phys_Dec;
      Bool_t                Hlt2Phys_TIS;
      Bool_t                Hlt2Phys_TOS;
      Double_t              BPVDIRA;
      Double_t              BPVIPCHI2;
      Double_t              BPVLTIME;
      Double_t              BPVVDCHI2;
      Double_t              BPVZ;
      Double_t              ETA;
      Double_t              MIPCHI2DV;
      Double_t              PHI;
      Double_t              PID;
      Double_t              VCHI2PDOF;

    };

    struct Mu {

      Double_t              MC12TuneV2_ProbNNe;
      Double_t              MC12TuneV2_ProbNNmu;
      Double_t              MC12TuneV2_ProbNNpi;
      Double_t              MC12TuneV2_ProbNNk;
      Double_t              MC12TuneV2_ProbNNp;
      Double_t              MC12TuneV2_ProbNNghost;
      Double_t              MC12TuneV3_ProbNNe;
      Double_t              MC12TuneV3_ProbNNmu;
      Double_t              MC12TuneV3_ProbNNpi;
      Double_t              MC12TuneV3_ProbNNk;
      Double_t              MC12TuneV3_ProbNNp;
      Double_t              MC12TuneV3_ProbNNghost;
      Double_t              CosTheta;
      Double_t              OWNPV_X;
      Double_t              OWNPV_Y;
      Double_t              OWNPV_Z;
      Double_t              OWNPV_XERR;
      Double_t              OWNPV_YERR;
      Double_t              OWNPV_ZERR;
      Double_t              OWNPV_CHI2;
      Int_t                 OWNPV_NDOF;
      Float_t               OWNPV_COV_;
      Double_t              IP_OWNPV;
      Double_t              IPCHI2_OWNPV;
      Double_t              ORIVX_X;
      Double_t              ORIVX_Y;
      Double_t              ORIVX_Z;
      Double_t              ORIVX_XERR;
      Double_t              ORIVX_YERR;
      Double_t              ORIVX_ZERR;
      Double_t              ORIVX_CHI2;
      Int_t                 ORIVX_NDOF;
      Float_t               ORIVX_COV_;
      Double_t              P;
      Double_t              PT;
      Double_t              PE;
      Double_t              PX;
      Double_t              PY;
      Double_t              PZ;
      Double_t              M;
      Int_t                 ID;
      Double_t              PIDe;
      Double_t              PIDmu;
      Double_t              PIDK;
      Double_t              PIDp;
      Double_t              ProbNNe;
      Double_t              ProbNNk;
      Double_t              ProbNNp;
      Double_t              ProbNNpi;
      Double_t              ProbNNmu;
      Double_t              ProbNNghost;
      Bool_t                hasMuon;
      Bool_t                isMuon;
      Bool_t                hasRich;
      Bool_t                hasCalo;
      Bool_t                L0Global_Dec;
      Bool_t                L0Global_TIS;
      Bool_t                L0Global_TOS;
      Bool_t                Hlt1Global_Dec;
      Bool_t                Hlt1Global_TIS;
      Bool_t                Hlt1Global_TOS;
      Bool_t                Hlt1Phys_Dec;
      Bool_t                Hlt1Phys_TIS;
      Bool_t                Hlt1Phys_TOS;
      Bool_t                Hlt2Global_Dec;
      Bool_t                Hlt2Global_TIS;
      Bool_t                Hlt2Global_TOS;
      Bool_t                Hlt2Phys_Dec;
      Bool_t                Hlt2Phys_TIS;
      Bool_t                Hlt2Phys_TOS;
      Double_t              BPVZ;
      Double_t              ETA;
      Double_t              MIPCHI2DV;
      Double_t              MM;
      Double_t              PHI;
      Double_t              PID;
      Double_t              TRCHI2DOF;
      Double_t              TRGHOSTPROB;      

    };

    struct Kp {

      Double_t              MC12TuneV2_ProbNNe;
      Double_t              MC12TuneV2_ProbNNmu;
      Double_t              MC12TuneV2_ProbNNpi;
      Double_t              MC12TuneV2_ProbNNk;
      Double_t              MC12TuneV2_ProbNNp;
      Double_t              MC12TuneV2_ProbNNghost;
      Double_t              MC12TuneV3_ProbNNe;
      Double_t              MC12TuneV3_ProbNNmu;
      Double_t              MC12TuneV3_ProbNNpi;
      Double_t              MC12TuneV3_ProbNNk;
      Double_t              MC12TuneV3_ProbNNp;
      Double_t              MC12TuneV3_ProbNNghost;
      Double_t              CosTheta;
      Double_t              OWNPV_X;
      Double_t              OWNPV_Y;
      Double_t              OWNPV_Z;
      Double_t              OWNPV_XERR;
      Double_t              OWNPV_YERR;
      Double_t              OWNPV_ZERR;
      Double_t              OWNPV_CHI2;
      Int_t                 OWNPV_NDOF;
      Float_t               OWNPV_COV_;
      Double_t              IP_OWNPV;
      Double_t              IPCHI2_OWNPV;
      Double_t              ORIVX_X;
      Double_t              ORIVX_Y;
      Double_t              ORIVX_Z;
      Double_t              ORIVX_XERR;
      Double_t              ORIVX_YERR;
      Double_t              ORIVX_ZERR;
      Double_t              ORIVX_CHI2;
      Int_t                 ORIVX_NDOF;
      Float_t               ORIVX_COV_;
      Double_t              P;
      Double_t              PT;
      Double_t              PE;
      Double_t              PX;
      Double_t              PY;
      Double_t              PZ;
      Double_t              M;
      Int_t                 ID;
      Double_t              PIDe;
      Double_t              PIDmu;
      Double_t              PIDK;
      Double_t              PIDp;
      Double_t              ProbNNe;
      Double_t              ProbNNk;
      Double_t              ProbNNp;
      Double_t              ProbNNpi;
      Double_t              ProbNNmu;
      Double_t              ProbNNghost;
      Bool_t                hasMuon;
      Bool_t                isMuon;
      Bool_t                hasRich;
      Bool_t                hasCalo;
      Bool_t                L0Global_Dec;
      Bool_t                L0Global_TIS;
      Bool_t                L0Global_TOS;
      Bool_t                Hlt1Global_Dec;
      Bool_t                Hlt1Global_TIS;
      Bool_t                Hlt1Global_TOS;
      Bool_t                Hlt1Phys_Dec;
      Bool_t                Hlt1Phys_TIS;
      Bool_t                Hlt1Phys_TOS;
      Bool_t                Hlt2Global_Dec;
      Bool_t                Hlt2Global_TIS;
      Bool_t                Hlt2Global_TOS;
      Bool_t                Hlt2Phys_Dec;
      Bool_t                Hlt2Phys_TIS;
      Bool_t                Hlt2Phys_TOS;
      Double_t              BPVIPCHI2;
      Double_t              BPVZ;
      Double_t              ETA;
      Double_t              MIPCHI2DV;
      Double_t              MM;
      Double_t              PHI;
      Double_t              PID;
      Double_t              TRCHI2DOF;
      Double_t              TRGHOSTPROB;

    };

    struct Km {

      Double_t              MC12TuneV2_ProbNNe;
      Double_t              MC12TuneV2_ProbNNmu;
      Double_t              MC12TuneV2_ProbNNpi;
      Double_t              MC12TuneV2_ProbNNk;
      Double_t              MC12TuneV2_ProbNNp;
      Double_t              MC12TuneV2_ProbNNghost;
      Double_t              MC12TuneV3_ProbNNe;
      Double_t              MC12TuneV3_ProbNNmu;
      Double_t              MC12TuneV3_ProbNNpi;
      Double_t              MC12TuneV3_ProbNNk;
      Double_t              MC12TuneV3_ProbNNp;
      Double_t              MC12TuneV3_ProbNNghost;
      Double_t              CosTheta;
      Double_t              OWNPV_X;
      Double_t              OWNPV_Y;
      Double_t              OWNPV_Z;
      Double_t              OWNPV_XERR;
      Double_t              OWNPV_YERR;
      Double_t              OWNPV_ZERR;
      Double_t              OWNPV_CHI2;
      Int_t                 OWNPV_NDOF;
      Float_t               OWNPV_COV_;
      Double_t              IP_OWNPV;
      Double_t              IPCHI2_OWNPV;
      Double_t              ORIVX_X;
      Double_t              ORIVX_Y;
      Double_t              ORIVX_Z;
      Double_t              ORIVX_XERR;
      Double_t              ORIVX_YERR;
      Double_t              ORIVX_ZERR;
      Double_t              ORIVX_CHI2;
      Int_t                 ORIVX_NDOF;
      Float_t               ORIVX_COV_;
      Double_t              P;
      Double_t              PT;
      Double_t              PE;
      Double_t              PX;
      Double_t              PY;
      Double_t              PZ;
      Double_t              M;
      Int_t                 ID;
      Double_t              PIDe;
      Double_t              PIDmu;
      Double_t              PIDK;
      Double_t              PIDp;
      Double_t              ProbNNe;
      Double_t              ProbNNk;
      Double_t              ProbNNp;
      Double_t              ProbNNpi;
      Double_t              ProbNNmu;
      Double_t              ProbNNghost;
      Bool_t                hasMuon;
      Bool_t                isMuon;
      Bool_t                hasRich;
      Bool_t                hasCalo;
      Bool_t                L0Global_Dec;
      Bool_t                L0Global_TIS;
      Bool_t                L0Global_TOS;
      Bool_t                Hlt1Global_Dec;
      Bool_t                Hlt1Global_TIS;
      Bool_t                Hlt1Global_TOS;
      Bool_t                Hlt1Phys_Dec;
      Bool_t                Hlt1Phys_TIS;
      Bool_t                Hlt1Phys_TOS;
      Bool_t                Hlt2Global_Dec;
      Bool_t                Hlt2Global_TIS;
      Bool_t                Hlt2Global_TOS;
      Bool_t                Hlt2Phys_Dec;
      Bool_t                Hlt2Phys_TIS;
      Bool_t                Hlt2Phys_TOS;
      Double_t              BPVIPCHI2;
      Double_t              BPVZ;
      Double_t              ETA;
      Double_t              MIPCHI2DV;
      Double_t              MM;
      Double_t              PHI;
      Double_t              PID;
      Double_t              TRCHI2DOF;
      Double_t              TRGHOSTPROB;

    };
  }

  class bs2st2buk_kmux_vars {

  public:
      UInt_t                nCandidate;
      ULong64_t             totCandidates;
      ULong64_t             EventInSequence;
      /* UInt_t                runNumber; */
      /* ULong64_t             eventNumber; */
      UInt_t                BCID;
      Int_t                 BCType;
      UInt_t                OdinTCK;
      UInt_t                L0DUTCK;
      UInt_t                HLT1TCK;
      UInt_t                HLT2TCK;
      ULong64_t             GpsTime;
      Short_t               Polarity;
      Int_t                 nPV;
      Float_t               PVX;
      Float_t               PVY;
      Float_t               PVZ;
      Float_t               PVXERR;
      Float_t               PVYERR;
      Float_t               PVZERR;
      Float_t               PVCHI2;
      Float_t               PVNDOF;
      Float_t               PVNTRACKS;

      bs2st2buk_kmux::Bs2st Bs2st;
      bs2st2buk_kmux::Bu    Bu;
      bs2st2buk_kmux::Mu    Mu;
      bs2st2buk_kmux::Kp    Kp;
      bs2st2buk_kmux::Km    Km;

      void attachTree(TTree * tree);

  };
}
